spring:
  datasource:
    url: jdbc:h2:mem:~/dio_h2
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8082
